services:
  web:
    build:
      context: ./.
      dockerfile: Dockerfile
      target: bedrock-access-gateway
    ports:
      - 3000:80
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
